loudsmilestudios/TetraForce

- engine/lobby.tscn
- ui/TetraForce.tres
- ui/monogram.tres
Intended to move forward on #1
> Initial pass on welcome screen and custom GUI theme

- enemies/knawblin.gd
- enemies/stalfos.gd
- engine/entity.gd
- game.gd
- player/player.gd
Fix for #11
Only syncs position, spritedir, and animation when they change or when the player list is updated.
Feel free to test it out and drop some feedback.
> Update network polling for position, direction, and animation.

- project.godot
These are not documented in godot docs but you can find some references
in https://github.com/godotengine/godot/issues/27230 and
https://github.com/godotengine/godot/issues/30881
> Change project settings for 2d games

- enemies/knawblin.gd
- enemies/knawblin.tscn
- enemies/stalfos.gd
- engine/entity.gd
- engine/helper_scipts/entity_helper.gd
- project.godot
Problem Statement
-----------------
Entity had static call that could be extracted to helper class to reduce line count and complexity in entity class
Solution
-----------------
Create Helper class for entity.
Move static func rand_direction to helper class and update enemies
Testing
-----------------
-----------------
> Entity Helper

- project.godot
Changed the "B" button to X and the "A" button to C
because almost all Keyboards outside of USA doesn't have the Z button next to X
> Changed Button Layout

- engine/entity.gd
- items/sword.gd
- items/sword.tscn
- player/player.gd
- player/player.tscn
Still to be done: visual/audio cue, increase damage for spin attack, network capability. I want to continue working on the visual cue at least, but won't be able to for several hours as of writing this, so anyone else is welcome to.
Also needs a solution to trapping mobs against wall, as the sword no longer disappears after making contact with the enemy and kills them instantly. I recommend a either pushback on the player, and possibly a stab animation/state, or invincibility frames for the enemy.
> Added spin attack.

- items/sword.gd
- items/sword.tscn
hopefully this looks a bit more natural. happy to tweak if needed.
> adjusted animation offsets for sword in spin attack and held position

- enemies/knawblin.gd
- enemies/stalfos.gd
- engine/entity.gd
- game.gd
- player/player.gd
Fixes some issues with my last PR #12 and also cleans up the code. Works on my machine, but obviously I'd recommend double checking before merging.
Syncing position is not optimal at the moment (left a comment with the optimal solution in `entity.gd`), I ran into issues with positions being synced properly on peer connection.
> Network Optimizations

- engine/lobby.gd
- engine/network.gd
Closes #24 
*was looking for the game in the wrong place and not stopping the network clock
> Fixes client crash on server disconnect

- ui/esc_menu.gd
- ui/esc_menu.tscn
- ui/hud.tscn
Added a simple pop up menu with Quit and Resume options for when the esc button is pressed.
> Added simple esc menu

- engine/main.gd
- engine/network.gd
In main.gd the main two changes are checking for the new cli arg (--empty-server-timeout) and passing the value through a few functions.  Also I combined some `if`s so there's just one place that sets the server as dedicated.
In network.gd, there are vars and functions added for running the timer, and they are called at start, when a player leaves (both start the timer if server is empty), and when a player joins (stop the timer if it's running).
> stop server if dedicated and no players after timeout

- Dockerfile
Sets timeout flag in Dockerfile to `300`
> Add timeout flag to Dockerfile

- engine/main.gd
- project.godot
> Replace Enet with WebSockets

- engine/keybinds.gd
- engine/main.gd
- engine/main.tscn
> Added Keybind support!

- .github/workflows/build_release.yml
For this to work with builds, it requires the secrets I sent to @fornclake privately, to be put in.
> Update everything to new environment

- engine/main.gd
- engine/server_api.gd
Changes:
- Refactored HTTPS to use a wrapper function called `_api_request`
- Parameter strings are now dynamically generated from dictionary objects
- Additional error checking
- Added functions to call the auth API
New Functions:
- login(username, password)
- register(username, password, email)
- get_profile()
- reset_password(username)
Authentication will be the first step in adding additional online features, such as user associated skins.
If there are any questions or concerns, please feel free to let me know. :smile:
> API Client | Refactor & Authentication

- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE/1_bug_report.md
- .github/ISSUE_TEMPLATE/2_feature_request.md
- .github/ISSUE_TEMPLATE/3_question.md
- .github/PULL_REQUEST_TEMPLATE.md
Adds Issue templates and GitHub CODEOWNERS
> Templates & CODEOWNERS

- tiles/blue_cannon.gd
- tiles/blue_cannon.tscn
Players and server host now agree cannon has kill
Cannon firing was not syncing. Joseph M did over the screen voodoo.
Fire a cannon with more than 1 person watching,
> Fixed cannon network issues

- addons/godot-multiplayer-development-tools/LICENSE
- addons/godot-multiplayer-development-tools/ReadMe.md
- addons/godot-multiplayer-development-tools/plugin.cfg
- addons/godot-multiplayer-development-tools/plugin.gd
- project.godot
Added [Loud Smile Studio's Multiplayer Development Tools](https://github.com/loudsmilestudios/godot-multiplayer-development-tools) into TetraForce project.
Open up branch in Godot then try the "Multistart" button. If successful, it should start two instances of the game.
> Add "Multistart" button

- .github/PULL_REQUEST_TEMPLATE.md
Add 'Was this tested in multiplayer?' question to PR template. This is to verify that people have tested in multiplayer before we even start the review process.
See the diff, the markdown file itself is used as the template.
> Added clarifying question to PR Template

- .github/ISSUE_TEMPLATE/1_bug_report.md
This PR adds a short section to request the game version in the bug report issue template.
> Update bug report to include game version
