engine/entity.gd, engine/entity.shader, game.gd
First iteration of this shader, with this colors can be swapped on the fly, and additional hurt textures are not required. For now, this is only linked up to replace the hurt textures.
To use this, a ShaderMaterial must be placed on the Sprite object of an entity and the shader must be assigned to it, if this is not done by hand, it will automatically be added to any entity with some default values. Additional work will need to be done to sync colors over the network.
For the "custom_colors" option to function properly, a spritesheet must be passed in where the color values are presented like so:
Skin: #FFFFFF (White)
Outline: #00000 (Black)
Accent: #FF00FF (Pink)
=> Entity Shader v1.0

player/player.tscn
This is a simple change to WalkUp Animation. I notice that the walkup animation doesn't play when the user make a small movement to up:
Old:
Fixed:
=> Changed WalkUp Animation

player/player.gd
Refactored loop_inventory() to use DRY and allow simultaneous button actions like bomb arrows and hammer dashes.
With a return in line 181 it would work exactly like the previous version, only processing the first matching button instead of all.
Somewhere down the road we might want to add the actions that passed the tests to an array and call a multi-action-function.
=> small improvement for button handling

engine/entity.gd, engine/network.gd, player/player.gd
Added a Room class. This class is useful for event that require room informations such as the enemy count in issue #7.
At the moment it contains arrays of the entities inside the room and provides player_entered, player_exited and enemies_defeated signals. The room is freed when everyone exits it.
Rooms can be accessed from the network singleton. Entities have a room variable that references the room they're in.
Current issues:
- Players' current room is updated only locally. So the rooms aren't properly synced and freed.
=> Room class

engine/settings.gd
The code to save preferences had a bug regarding the concatenation of strings. I guess it was intended to have a subfolder "tetraforce" and a file "preferences.tf" in there.
As it turns out, that subfolder was created, but it never contained any items. Instead, a file called "tetraforcepreferences.tf" was created.
This change removed the unnecessary subfolder (because Godot sets the user:// root folder to a subdirectory of the project name already) and switches the extension to json to better reflect its contents.
If you checked out an earlier version of the game, you still have to manually remove the empty "tetraforce" (all lowercase!) directory and "tetraforcepreferences.tf" settings file.
=> changed save location for preferences

player/player.gd, ui/inventory/inventory.gd
inventory.gd was using item_resources, instead of items, get item names.
Since item_resources isn't used anywhere else, I removed it and update_item_resources(), which was causing errors in multiplayer.
=> Remove item_resources and update_item_resources()

.gitignore, engine/characterselect.gd
This should be a fix for https://github.com/fornclake/TetraForce/issues/65 that is handled by taking the first 8 characters of a name, followed by a plus sign, if the name is more than 9 characters.
=> Potential fix to handle names that are too long

.github/workflows/build_dev_server.yml, .github/workflows/build_godot.yml, .github/workflows/build_release.yml, .github/workflows/build_stage_server.yml
Updates CI/CD pipeline to split project in stages. This allows the production environment to remain stable, while stage and dev environments can have non-tested code.
Pipeline: Dev -> Stage -> Production
Dev: Any manual workflow trigger can create a dev image with a custom tag. The custom tag can then be deployed to a dev environment (I'll write more documentation about this at some point)
Stage: `master` branch
Production: GitHub release & correlating tag
Every time there is a release to production, the container will get the `latest` tag. Anytime there is a push to master, the container will get the `stage` tag. The similar pipeline exists currently for the infrastructure.
Closes https://github.com/josephbmanley/tetraforce-infrastructure/issues/13
=> Additional improvements to CI/CD pipeline

.github/workflows/build_dev_server.yml, .github/workflows/build_release.yml, .github/workflows/build_stage_server.yml
When building the docker images on forks, the build would fail because it would not have permissions to push to the main TetraForce repository. This has been solved by formatting the Git repo name and using it to push to the fork's Docker repo.
=> PIPELINE: Fixed Docker Push Errors on Forks

.github/workflows/build_dev_server.yml, .github/workflows/build_godot.yml, .github/workflows/build_release.yml
Notable changes:
- Removed all uses of `set-env`
- Seperated out Linux and Windows build jobs
- Added file extension to Linux builds
=> PIPELINE: Fix pipeline

engine/main.gd
Moved the logic for `empty-server-timeout` to its own function, fixed it up a bit, and added some logging.
At some point we talked about the default should be `0` because that will be easiest for anyone that wants to run their own server.  That does mean we'll have to pass `--empty-server-timeout=60` for the AWS servers.
And the reason for the extra user friendly validation and logging is for the same reason, someone other than devs may try to set up a server, and I think it would be best if it's easy to see if they did something wrong.
=> fixing up empty-server-timeout

entities/player/player.gd
It also hides the player's name in multiplayer.
=> Player name is now hidden in single player.

engine/network.gd
Old set_state function was removed. New `add_state` function wraps `set_state`
This fixes a bug that causes the game to lock up when picking up an item.
=> Fix missing `add_state` function

.github/workflows/build_godot.yml, .github/workflows/build_release.yml
- Remove OSX from debug builds
- Fix release builds
- Installs Godot from godotengine.org instead of brew
Closes #190
=> OSX Build Changes

.github/stale.yml
This PR adds `.github/stale.yml` which will mark issues `stale` after 60 days and close stale issues after a week.
Issues marked as an `enchancement`, `improvement`, or `documentation` will never be labeled stale.
=> Automatically handle stale issues

engine/global.gd, sound/sound.gd
Fades out music when travelling between maps. Makes the shrine/overworld transition feel less jarring.
Note that I'm not 100% sure I've done this correctly.
Walk through a map transition (I tested with shrine-overworld), and listen to the volume of the music.
(Note that zone transitions don't have this apply to them - I'm relying on the fadeout time to give time for the fadeout.)
=> Fade out music when changing maps

engine/network.gd
*This is the issue that got resolved - Closes #279
Chest Items were not properly networked. They are now working
Place any chest in Shrine, test in Multiplayer
[**Has this been tested in multiplayer?**](https://github.com/loudsmilestudios/TetraForce/wiki/How-to-test-multiplayer) *yes*
=> Network Fixed

sound/sound.gd
Hopefully a better music fading implementation.
This one will create fade-outs. It can also perform fade-ins, but this does not occur by default as it tends to sound worse with current tracks.
(A specific problem I've noticed that is semi-related to this is that apparently there are cases where two maps have the same music track and are directly connected, and in this case the fadeout is unnecessary and probably not wanted. However I'm not sure how to solve this without tagging the entrances.)
+ Travel to the village, leave the village, go back in the village, enter buildings/etc.
+ Get a game over, confirm that doesn't break anything
[**Has this been tested in multiplayer?**](https://github.com/loudsmilestudios/TetraForce/wiki/How-to-test-multiplayer) *yes*
=> Better music fading implementation (automatic fadeouts)

engine/game.gd, engine/global.gd, engine/main.gd, engine/network.gd, engine/network_object.gd, entities/collectables/spiritpearl.gd, entities/collectables/spiritpearl.tscn, maps/shrine.tmx, tiles/chest.gd, ui/hud/hud.gd, ui/hud/hud.tscn, ui/inventory/inventory.gd
When attempting to Sync Collectables, we unknowingly caused issues among Sharing Items, and Persistent State. My Goal was to network the Spirit Pearls, but in so doing I found the flaws in the code. This PR Remedies all of these as well as my original goal of Properly adding Spirit Pearls. Some more code clean up may be required, but overall things are set and working.
Open a Chest anywhere, or add to the Shrine during a multiplayer Session. Regardless whether the players are on the same map or not, the items will update for everyone, and the chest will be open for everyone, and remain open. 
[**Has this been tested in multiplayer?**](https://github.com/loudsmilestudios/TetraForce/wiki/How-to-test-multiplayer) 
The whole point of this PR, so you bet your boots :)
=> *FIX* Sync Multiplayer Objects

.github/workflows/build_release.yml
This PR updates the build system to better support deployments.
On publish:
- Docker images will now be deployed to ECR & be the default version to run when a new server is requested
- After a new build is released, it will clear the cached version
Only way to test is to run a new release
=> Push Docker Image To ECR & Clear Build Cache

engine/network.gd
In multiplayer game
In singleplayer game without restart
`network.pid` needed to be set to `1`, its default value, when exiting a game. Otherwise that value is malformed causing issues when hosting a game.
1. Join multiplayer game (not as host)
2. Exit game to main menu
3. Start singleplayer game
[**Has this been tested in multiplayer?**](https://github.com/loudsmilestudios/TetraForce/wiki/How-to-test-multiplayer) yes
=> BUGFIX: Reset `network.pid` on exit

ui/options/gameplay.tscn, ui/options/options.tscn, ui/options/pvp_toggle.gd, ui/options/sound.gd, ui/options/sound.tscn
- PvP Toggle is now settable in options
- Volume slider can now go to zero!
1. You can test PvP changes by changing PvP toggle before joining a multiplayer game and seeing results
2. Volume changes can be easily done by trying to drag volume to zero
[**Has this been tested in multiplayer?**](https://github.com/loudsmilestudios/TetraForce/wiki/How-to-test-multiplayer) *kinda?* Tested with same configuration file, not cross system
=> PvP Toggle added to options & Volume Bugfix

engine/network_object.gd, maps/dungeon1.tmx, maps/shrine.tmx
This is a bugfix that allows enter properties to work for persistent values within the string based saving system.
=> Update `network_object.gd` to set states as strings
